{% set name = "kfp-tekton" %}
{% set version = "0.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kfp-tekton-{{ version }}.tar.gz
  sha256: 6954f8fc743f75bcf08f7dc9e52cf15dc5dda1474e12f7e0e305c34d04054ecf

build:
  number: 0
  noarch: python
  entry_points:
    - dsl-compile-tekton = kfp_tekton.compiler.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
    - requests
  run:
    - kfp ==1.0.4
    - python >=3.5

test:
  imports:
    - kfp_tekton
    - kfp_tekton.compiler
  commands:
    - pip check
    - dsl-compile-tekton --help
  requires:
    - pip

about:
  home: https://github.com/kubeflow/kfp-tekton/
  summary: Tekton Compiler for Kubeflow Pipelines
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ckadner
    - Tomcli
    - animeshsingh
